### ISSUE TITLE
hugo --gc --minified failing on netlify

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/pages#25]
After pull request #24 hugo --gc --minified started failing
And therefore the deploy on netlify failed as well

Had to change deploy command to `hugo` in `netlify.toml`
Not sure what are the implications of this
![image](https://user-images.githubusercontent.com/1489570/126402014-c8a2c64c-6e2e-4f69-b790-fa85d6215ad8.png)

**Comment by ddazal** [comment]
Fixed by d221c2dd67c69f3db2ae678dfe72f7fd32a1af27. It was a missing `"` in two `.md` files
